[project]
name = "autgolem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AutGolemgh", email = "philipp.bitschnau123@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.14.0",
]

[tool.maturin]
module-name = "autgolem._core"
python-packages = ["autgolem"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
